### ISSUE TITLE
2019-09 - remote meetup #2

### ISSUE THREAD

**Issue by viniarck** [elixirup/remote-meetup#2]
Hi, all. @davearonson will give a lighting talk about some differences between prepending and appending on lists, also he'll talk about mutation testing (language agnostic). We look forward to having as many participants as possible, @davearonson said he'll be able to present on either:

- Mon, Sep 23th, 2PM-3PM or 3PM-4PM (EDT)
- Wed, Sep 25th, 2PM-3PM or 3PM-4PM (EDT)

Whichever timeslot gets the highest number of votes will be the next meetup date, if you're going to attend, please [click here](https://zvite.co/i/_m99psZT) to RSVP and vote. If you need help to convert from EDT to your timezone, check [this website](https://www.worldtimebuddy.com/)

**Comment by viniarck** [comment]
By Sep 20th, I'll post the voting results and also the URL to join the meetup.

**Comment by thojanssens** [comment]
If I'm not wrong that's around 1 AM in Asia 😭

**Comment by viniarck** [comment]
Indeed @thojanssens : ) 

Currently, most of participants are based in North/South America and Europe.

**Comment by thojanssens** [comment]
Make it at least the slot 2PM-3PM for people located in Asia bro 🙏

**Comment by viniarck** [comment]
Hi, All. Just a quick update. So far, the highest number of votes, 7+ on Sep 23th, 2PM EST. The voting pool will close on Friday morning.  

@thojanssens looks like it's going to be on the 2PM-3PM slot : )

**Comment by viniarck** [comment]
The highest number of votes were on Mon, Sep 23th, 2PM EDT (New York time zone). See you all soon.

**Comment by viniarck** [comment]
Here's the link for the meetup: https://meetinglab.zoho.com/meeting/join?key=1080330433

**Comment by viniarck** [comment]
The talk is available on YouTube https://www.youtube.com/watch?v=lCjeKcSN41I
