### ISSUE TITLE
2019-11 remote-meetup #3 "Why you should learn Elixir"

### ISSUE THREAD

**Issue by viniarck** [elixirup/remote-meetup#3]
Hi, all. @gpad will present the following [talk](https://2019.ploneconf.org/talks/why-you-shuld-learn-elixir/) on this month's remote-meetup:

In this talk I'll talk about Elixir, Erlang and the BEAM, the Virtual Machine that does the magic. I'll show you what are the main features of these strange beasts and why you should care about it. Why a platform invented and developed between the '80 and '90 to solve a specific problem, is so actual, so interesting and so imitated by so many languages and libraries. If you are curious, brave and a little mad you can find some interesting ideas to use also in your favourite language and framework.

He'll be able to present on either:

https://zvite.co/i/qvMS3ywU

Whichever timeslot gets the highest number of votes will be the next meetup date, if you're going to attend, please click here to RSVP and vote.

**Comment by adolfont** [comment]
This is great!

**Comment by qbeek42** [comment]
voted!

**Comment by viniarck** [comment]
The result of the voting pool will be available on this Friday, Nov 15th. I'll post the link to attend the meetup on this thread in the next days.

**Comment by viniarck** [comment]
Fri Nov 29th at 3:30 PM CET had the highest number (9) of votes. I'll post the link for the event soon, just so you can subscribe this event in your calendar.

**Comment by viniarck** [comment]
Here's the link to join the meetup: 
https://meetinglab.zoho.com/meeting/join?key=1098766851
